/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportadora;

import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Wesley
 */
public class AddAuxiliarUI extends javax.swing.JFrame {
    /**
     * Classe responsável pela criação do sistema gráfico do adicionamento de auxiliares
     * @version 1.0 beta
     * @author Wesley Ozebe
     */
static ArrayList<AddAuxiliar> auxiliares = new ArrayList<AddAuxiliar>();
AddAuxiliar auxiliar;
Icon erroIcone = new ImageIcon(getToolkit().createImage(getClass().getResource("/transportadora/images/Erro.png")));
    /**
     * Creates new form AddAuxiliarUI
     */
    public AddAuxiliarUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomeAuxiliarField = new javax.swing.JTextField();
        telefoneAuxiliarField = new javax.swing.JTextField();
        cpfAuxiliarField = new javax.swing.JTextField();
        salarioAuxiliarField = new javax.swing.JTextField();
        valorHoraAuxiliarField = new javax.swing.JTextField();
        horasTrabalhadasAuxiliarField = new javax.swing.JTextField();
        adicionarAuxiliarBotao = new javax.swing.JToggleButton();

        jLabel4.setText("jLabel4");

        setTitle("Adicionar Auxiliar");

        jLabel1.setText("Nome");

        jLabel2.setText("Telefone");

        jLabel3.setText("CPF");

        jLabel5.setText("Salário");

        jLabel6.setText("Valor da hora");

        jLabel7.setText("Horas Trabalhadas");

        jLabel8.setText("Adicionar Auxiliar");

        adicionarAuxiliarBotao.setText("Adicionar!");
        adicionarAuxiliarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarAuxiliarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horasTrabalhadasAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salarioAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorHoraAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefoneAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel8)))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(adicionarAuxiliarBotao)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(telefoneAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpfAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(salarioAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(valorHoraAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(horasTrabalhadasAuxiliarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adicionarAuxiliarBotao)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarAuxiliarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarAuxiliarBotaoActionPerformed
       try{
       String nomeAuxiliar = nomeAuxiliarField.getText();
       String telefoneAuxiliar = telefoneAuxiliarField.getText();
       String cpfAuxiliar = cpfAuxiliarField.getText();
       double salarioAuxiliar = Double.parseDouble(salarioAuxiliarField.getText());
       double valorDaHoraAuxiliar = Double.parseDouble(valorHoraAuxiliarField.getText());
       double horasTrabalhadasAuxiliar = Double.parseDouble(horasTrabalhadasAuxiliarField.getText());
       auxiliar = new AddAuxiliar(cpfAuxiliar, nomeAuxiliar, telefoneAuxiliar, salarioAuxiliar, valorDaHoraAuxiliar, horasTrabalhadasAuxiliar);
       
       auxiliares.add(auxiliar);
       }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Valores incorretos inseridos", "Erro", JOptionPane.ERROR_MESSAGE, erroIcone);
               
                
            }
       
    }//GEN-LAST:event_adicionarAuxiliarBotaoActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JToggleButton adicionarAuxiliarBotao;
    public static javax.swing.JTextField cpfAuxiliarField;
    public static javax.swing.JTextField horasTrabalhadasAuxiliarField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JTextField nomeAuxiliarField;
    public static javax.swing.JTextField salarioAuxiliarField;
    public static javax.swing.JTextField telefoneAuxiliarField;
    public static javax.swing.JTextField valorHoraAuxiliarField;
    // End of variables declaration//GEN-END:variables
}
