/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportadora;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Wesley
 */
public class AddCidade extends javax.swing.JFrame {
    /**
     * Classe responsável pela criação do sistema gráfico do adicionamento de cidades
     * @version 1.0 beta
     * @author Wesley Ozebe
     */
    static ArrayList<Estado> estado = new ArrayList<Estado>();
    static ArrayList<Cidade> cidades = new ArrayList<Cidade>();

    /**
     * Creates new form AddCidade
     */
    public AddCidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeCidadeField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeEstadoField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ufEstadoField = new javax.swing.JTextField();
        adicionarCidadeEstadoBotao = new javax.swing.JButton();

        setTitle("Adicionar cidade ou estado");
        setMaximumSize(new java.awt.Dimension(368, 209));
        setMinimumSize(new java.awt.Dimension(368, 209));
        setPreferredSize(new java.awt.Dimension(368, 209));
        setResizable(false);
        setSize(new java.awt.Dimension(368, 209));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jLabel1.setText("Adicionar Cidade");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 170, 16);
        getContentPane().add(nomeCidadeField);
        nomeCidadeField.setBounds(200, 40, 120, 24);

        jLabel2.setText("Nome da Cidade");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 92, 16);

        jLabel3.setText("Nome do Estado");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 150, 16);
        getContentPane().add(nomeEstadoField);
        nomeEstadoField.setBounds(200, 70, 120, 24);

        jLabel4.setText("UF do estado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 140, 16);
        getContentPane().add(ufEstadoField);
        ufEstadoField.setBounds(200, 100, 120, 24);

        adicionarCidadeEstadoBotao.setText("Adicionar!");
        adicionarCidadeEstadoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCidadeEstadoBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(adicionarCidadeEstadoBotao);
        adicionarCidadeEstadoBotao.setBounds(200, 130, 120, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarCidadeEstadoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCidadeEstadoBotaoActionPerformed
           
        if ((estado.isEmpty() == true || BuscarEstadoCidade.buscaPorEstado(nomeEstadoField.getText()) == 0) && ErrosDeInsercao.ErroAoInserirSigla(ufEstadoField.getText()) == false) {
            // int distancia = Integer.parseInt(distanciaField.getText());
            Estado e1 = new Estado(ufEstadoField.getText(), nomeEstadoField.getText());
            Cidade c1 = new Cidade(nomeCidadeField.getText());

            e1.incluirCidade(c1);

            cidades.add(c1);
            estado.add(e1);

            JOptionPane.showMessageDialog(null, "Estado e cidade adicionada com exito");

        } else if ((estado.isEmpty() == false && BuscarEstadoCidade.buscaPorEstado(nomeEstadoField.getText()) == 1) && ErrosDeInsercao.ErroAoInserirSigla(ufEstadoField.getText()) == false) {

            for (int n = 0; n < estado.size(); n++) {
                if (estado.get(n).getNome().equals(nomeEstadoField.getText())) {

                    //   int distancia = Integer.parseInt(distanciaField.getText());
                    Cidade c1 = new Cidade(nomeCidadeField.getText());
                    estado.get(n).incluirCidade(c1);
                    JOptionPane.showMessageDialog(null, "cidade adicionada com exito");
                }
            }

        } else{
            JOptionPane.showMessageDialog(null, "Dados inseridos de forma incorreta", "ERRO", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_adicionarCidadeEstadoBotaoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton adicionarCidadeEstadoBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JTextField nomeCidadeField;
    public static javax.swing.JTextField nomeEstadoField;
    public static javax.swing.JTextField ufEstadoField;
    // End of variables declaration//GEN-END:variables
}
