/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportadora;

import java.util.ArrayList;

/**
 *
 * @author Wesley
 */
public class AddMotorista extends javax.swing.JFrame {
    /**
     * Classe responsável pela criação do sistema gráfico do adicionamento de cidades
     * @version 1.0 beta
     * @author Wesley Ozebe
     */
    static ArrayList<Motorista> motoristas = new ArrayList<Motorista>();
    Motorista motoristaAdicionado;
    /**
     * Creates new form AddMotorista
     */
    public AddMotorista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adicionarMotoristaBotao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nomeMotoristaAreaTexto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cpfMotoristaAreaTexto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefoneMotoristaAreaTexto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        salarioMotoristaAreaTexto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cnhMotoristaAreaTexto = new javax.swing.JTextField();

        setTitle("Motorista");
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(395, 315));
        setResizable(false);

        jLabel1.setText("Adicionar um novo motorista");

        adicionarMotoristaBotao.setText("Adicionar");
        adicionarMotoristaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarMotoristaBotaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF(apenas Números):");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Salário:");

        salarioMotoristaAreaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioMotoristaAreaTextoActionPerformed(evt);
            }
        });

        jLabel6.setText("CNH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeMotoristaAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salarioMotoristaAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cnhMotoristaAreaTexto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(telefoneMotoristaAreaTexto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cpfMotoristaAreaTexto, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(adicionarMotoristaBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeMotoristaAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpfMotoristaAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telefoneMotoristaAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(salarioMotoristaAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cnhMotoristaAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(adicionarMotoristaBotao)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarMotoristaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarMotoristaBotaoActionPerformed
        Double salarioMotorista = Double.parseDouble(salarioMotoristaAreaTexto.getText());
        motoristaAdicionado = new Motorista(cpfMotoristaAreaTexto.getText(), nomeMotoristaAreaTexto.getText(), telefoneMotoristaAreaTexto.getText(), salarioMotorista, cnhMotoristaAreaTexto.getText());
        motoristas.add(motoristaAdicionado);

    }//GEN-LAST:event_adicionarMotoristaBotaoActionPerformed

    private void salarioMotoristaAreaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioMotoristaAreaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioMotoristaAreaTextoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton adicionarMotoristaBotao;
    public static javax.swing.JTextField cnhMotoristaAreaTexto;
    public static javax.swing.JTextField cpfMotoristaAreaTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField nomeMotoristaAreaTexto;
    public static javax.swing.JTextField salarioMotoristaAreaTexto;
    public static javax.swing.JTextField telefoneMotoristaAreaTexto;
    // End of variables declaration//GEN-END:variables

}
