/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportadora;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Wesley
 */
public class ViagemSaida extends javax.swing.JFrame {

    static ArrayList<Viagem> viagens = new ArrayList<Viagem>();
    AddAuxiliarUI adicionarAuxiliares = new AddAuxiliarUI();
    /**
     * Creates new form ViagemSaida
     */
    public ViagemSaida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        escolhaDeVeiculo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        seletorDeMotorista = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        seletorDeEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        seletorDeCidade = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        addViagemBotao = new javax.swing.JButton();
        dataSaidaField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pesoField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        volumeField = new javax.swing.JTextField();
        dadosDoVeiculoSelecionado = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        setorMotoristaBotao = new javax.swing.JButton();
        motoristaLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setTitle("Adicionar Viagem");
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(482, 435));
        setResizable(false);
        setSize(new java.awt.Dimension(482, 435));

        jLabel1.setText("Saída");

        escolhaDeVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caminhão", "Carreta", "Bitrem", "Furgão" }));
        escolhaDeVeiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                escolhaDeVeiculoItemStateChanged(evt);
            }
        });
        escolhaDeVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolhaDeVeiculoActionPerformed(evt);
            }
        });

        jLabel2.setText("Escolha o veículo");

        jLabel4.setText("Escolha o motorista");

        seletorDeMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorDeMotoristaActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Estado");

        seletorDeEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seletorDeEstadoItemStateChanged(evt);
            }
        });
        seletorDeEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorDeEstadoActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cidade");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Origem");

        addViagemBotao.setText("Adicionar Viagem");
        addViagemBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addViagemBotaoActionPerformed(evt);
            }
        });

        dataSaidaField.setText("dd/MM/yyyy");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Data de saída");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Peso em KG's");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Volume");

        dadosDoVeiculoSelecionado.setText("Dados do veículo");
        dadosDoVeiculoSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosDoVeiculoSelecionadoActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Adicionar auxiliares");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        setorMotoristaBotao.setText("Setar motorista");
        setorMotoristaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorMotoristaBotaoActionPerformed(evt);
            }
        });

        jLabel10.setText("Informações da carga");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(seletorDeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(pesoField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                    .addComponent(volumeField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(dataSaidaField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(8, 8, 8))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(seletorDeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(seletorDeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(dadosDoVeiculoSelecionado))
                            .addComponent(escolhaDeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(setorMotoristaBotao)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(addViagemBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(motoristaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(escolhaDeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seletorDeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dadosDoVeiculoSelecionado)
                    .addComponent(setorMotoristaBotao))
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seletorDeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seletorDeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motoristaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataSaidaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(addViagemBotao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escolhaDeVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolhaDeVeiculoActionPerformed
        // JOptionPane.showMessageDialog(null, escolhaDeVeiculo.getSelectedItem());

        //  if(escolhaDeVeiculo.getSelectedItem() == "Caminhão"){
        //    JOptionPane.showMessageDialog(null, "Escolheu caminhão");
        // }
    }//GEN-LAST:event_escolhaDeVeiculoActionPerformed

    private void escolhaDeVeiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_escolhaDeVeiculoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_escolhaDeVeiculoItemStateChanged

    private void seletorDeMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorDeMotoristaActionPerformed
        
    }//GEN-LAST:event_seletorDeMotoristaActionPerformed

    private void seletorDeEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorDeEstadoActionPerformed
        String nomeEstadoSelecionado = (String) seletorDeEstado.getSelectedItem();

        for (int n = 0; n < AddCidade.estado.size(); n++) {
            if (AddCidade.estado.get(n).getNome().equals(nomeEstadoSelecionado)) {
                seletorDeCidade.removeAllItems();
                int quantiaDeCidadesNoEstado = AddCidade.estado.get(n).tamanhoCidades();
                for (int j = 0; j < quantiaDeCidadesNoEstado; j++) {
                seletorDeCidade.addItem(AddCidade.estado.get(n).getCidades().get(j).getNome());

                }

            }
        }
    }//GEN-LAST:event_seletorDeEstadoActionPerformed

    private void seletorDeEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seletorDeEstadoItemStateChanged

    }//GEN-LAST:event_seletorDeEstadoItemStateChanged

    private void addViagemBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addViagemBotaoActionPerformed
        //pega a data que foi inserida no dataSaidaField e coloca na ArrayList viagens como o primeiro argumento do construtor do tipo Date
        //arrumar bug, quando a data tá errada ele continua a executar o código(parcialmente arrumado)
        Date dts;
        String dataSaida = dataSaidaField.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            dts = sdf.parse(dataSaida);
        } catch (ParseException pe) {
            JOptionPane.showMessageDialog(null, pe.getMessage() + "\nData inserida de forma incorreta", "Erro", JOptionPane.ERROR_MESSAGE);
            dts = null;
            
        }
        //----------------------------------------------------------------------------------------------------
        if(dts != null){
        String pesoString = pesoField.getText().replace(",", ".");
        String volumeString = volumeField.getText().replace(",", ".");
        double peso = Double.parseDouble(pesoString);
        double volume = Double.parseDouble(volumeString);

        //verificar motorista escolhido a partir do seletorDeMotorista----------------------------------------
        String nomeMotoristaSelecionado = (String) seletorDeMotorista.getSelectedItem();
        int posicaoMotoristaSelecionado = 0;
        for (int i = 0; i < AddMotorista.motoristas.size(); i++) {
            if (AddMotorista.motoristas.get(i).getNome().equals(nomeMotoristaSelecionado)) {
                posicaoMotoristaSelecionado = i;
            }

        }
        //----------------------------------------------------------------------------------------------------
        //verificar a existência de auxilaires que ajudaram na carga do veiculo escolhido---------------------
        
        //----------------------------------------------------------------------------------------------------
        Viagem viagem1 = new Viagem(dts, peso, volume, AddMotorista.motoristas.get(posicaoMotoristaSelecionado));
        viagens.add(viagem1);
        }

    }//GEN-LAST:event_addViagemBotaoActionPerformed

    private void dadosDoVeiculoSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosDoVeiculoSelecionadoActionPerformed
       
       
    }//GEN-LAST:event_dadosDoVeiculoSelecionadoActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        adicionarAuxiliares.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void setorMotoristaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorMotoristaBotaoActionPerformed
        //procura o motorista baseado no que foi selecionado no seletorDeMotorista------------------
        try{
        String nomeMotoristaSelecionado = (String) seletorDeMotorista.getSelectedItem();
        int posicaoMotoristaSelecionado = 0;
        for (int i = 0; i < AddMotorista.motoristas.size(); i++) {
            if (AddMotorista.motoristas.get(i).getNome().equals(nomeMotoristaSelecionado)) {
                posicaoMotoristaSelecionado = i;
            }

        }
        //------------------------------------------------------------------------------------------
        if(AddMotorista.motoristas.get(posicaoMotoristaSelecionado).emViagem == false){
            AddMotorista.motoristas.get(posicaoMotoristaSelecionado).emViagem = true;
            motoristaLabel.setText("Motorista: " + AddMotorista.motoristas.get(posicaoMotoristaSelecionado).getNome());
        } else{
            JOptionPane.showMessageDialog(null, "O motorista selecionado já está em uma viagem!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Necessita adicionar pelo menos um motorista", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_setorMotoristaBotaoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton addViagemBotao;
    public static javax.swing.JButton dadosDoVeiculoSelecionado;
    public static javax.swing.JTextField dataSaidaField;
    public static javax.swing.JComboBox<String> escolhaDeVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    public static javax.swing.JLabel motoristaLabel;
    public static javax.swing.JTextField pesoField;
    public static javax.swing.JComboBox<String> seletorDeCidade;
    public static javax.swing.JComboBox<String> seletorDeEstado;
    public static javax.swing.JComboBox<String> seletorDeMotorista;
    public static javax.swing.JButton setorMotoristaBotao;
    public static javax.swing.JTextField volumeField;
    // End of variables declaration//GEN-END:variables
}
